#pragma once

//GLOBAL DEFINES FOR PUYO PUYO
#define SCREEN_WIDTH  384
#define SCREEN_HEIGHT  630  

#define PIECE_SPEED  10  

#define BLOCK_START_X  96
#define BLOCK_START_Y  31


#define FRAMES_PER_SECOND  2
#define FRAME_RATE  1000/FRAMES_PER_SECOND

#define PIECE_WIDTH 64
#define PIECE_HEIGHT 62

//POSITIONS OF THE COLORS 
//[R][P]
//[Y][G]
#define RED_POSITION_X 0
#define RED_POSITION_Y 0 
#define YELLOW_POSITION_X 0
#define YELLOW_POSITION_Y 62
#define PURPLE_POSITION_X 0
#define PURPLE_POSITION_Y 64 
#define GREEN_POSITION_X 64
#define GREEN_POSITION_Y 62
